# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner_app', '0002_auto_20170318_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='generate_lunch',
            field=models.BooleanField(default=True),
        ),
    ]
